site_name: Sustainable Investment Group @ UCSD Wiki
site_url: https://sigatucsd.github.io/wiki/
repo_url: https://github.com/SIGatUCSD/wiki/
docs_dir: docs

nav:
  - Home: index.md
  - General:
    - 'History': 'general/history.md'
  - Sustainability:
    - 'Introduction': 'sust/intro.md'
  - Equity Research:
    - 'Introduction': 'er/intro.md'
  - Quantitative Analysis:
    - 'Introduction': 'quant/intro.md'
  - Research and Development:
    - 'Introduction': 'rd/intro.md'
theme:
  name: 'material'
  palette:
    scheme: slate
    primary: green
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
